DROP TABLE IF EXISTS `quote`;
CREATE TABLE `quote` (
  `id` int AUTO_INCREMENT PRIMARY KEY,
  `quotes` varchar(255)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

