DROP TABLE IF EXISTS `quote`;
CREATE TABLE `quote` (
  `id` int NOT NULL AUTO_INCREMENT,
  `quotes` varchar(255) ,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

